// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFb4khn5JsF2Pf5_MGCpoFJia1FMTJyHA',
    appId: '1:657699133158:web:699760d886876d76688d27',
    messagingSenderId: '657699133158',
    projectId: 'flutter-ux-design-c357c',
    authDomain: 'flutter-ux-design-c357c.firebaseapp.com',
    storageBucket: 'flutter-ux-design-c357c.appspot.com',
    measurementId: 'G-KQR9VSHR9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKN4L_cwI2HVkgAhJnAwcHIu_jlFq5NfA',
    appId: '1:657699133158:android:067710edfeda9128688d27',
    messagingSenderId: '657699133158',
    projectId: 'flutter-ux-design-c357c',
    storageBucket: 'flutter-ux-design-c357c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQB-bqwuxqBMtXpfvSqcc6uHyNVgJK_DI',
    appId: '1:657699133158:ios:fd9dc89b3f3edd5d688d27',
    messagingSenderId: '657699133158',
    projectId: 'flutter-ux-design-c357c',
    storageBucket: 'flutter-ux-design-c357c.appspot.com',
    iosClientId: '657699133158-306i3qeqhg1bfj24fi15bmt67c4194q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUxDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQB-bqwuxqBMtXpfvSqcc6uHyNVgJK_DI',
    appId: '1:657699133158:ios:fd9dc89b3f3edd5d688d27',
    messagingSenderId: '657699133158',
    projectId: 'flutter-ux-design-c357c',
    storageBucket: 'flutter-ux-design-c357c.appspot.com',
    iosClientId: '657699133158-306i3qeqhg1bfj24fi15bmt67c4194q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUxDesign',
  );
}
